<a href="https://colab.research.google.com/github/danek121/machine-learning-course/blob/main/learning_machine/01_basics/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import bibliotek numpy, pandas oraz sklearn
import numpy as np
import pandas as pd
import sklearn

#wypisanie wersji biblioteki sklearn
sklearn.__version__

'1.6.1'

In [3]:
#generowanie danych
#utworzenie obiektów dateframe gdzie kluczem sa nazwy kolumn
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

# tworzenie zmiennej i utworzenie obiektu dateframe

df_raw = pd.DataFrame(data=data)
df_raw




size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [5]:
#tworzenie kopii danych oraz wyswietlenie informacji o obiekcie
df = df_raw.copy()
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes


In [6]:
#zmiana typu danych
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

  df['weight'] = df['weight'].astype('float')

  df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      object  
 2   gender  5 non-null      object  
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      object  
dtypes: category(1), float64(2), object(3)
memory usage: 469.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      object  
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      object  
dtypes: category(2), float64(2), object(2)
memory usage: 566.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 

In [7]:
#wyswietlenie podstawowych statystyk obiektu dateframe
#describe wyswietla tylko numeryczne kolumny
df.describe()

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [8]:
#transponujemy kolumny
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [11]:
#dodajemy wyswietlanie statystyki ze zmiennymi kategorycznymi

df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [12]:
#wyswietlanie obiektu df
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [14]:
#przygotowanie danych
#le.fit_transform zwraca tablice numeryczna(number array)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [15]:
#przypisanie zmienionych danych do (no = 0;yes=1)
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [16]:
#zmiana do pierwotnego stanu
df['bought'] = le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [19]:
#importowanie onehotencoder(biblioteka do pobierania danych) z sklearn preprocessing
#utworzenie instancje klasy

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])


OneHotEncoder(sparse_output=False)

In [20]:
#wykonanie kodowania uzywajac transform
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [21]:
#wyswietlanie kategorii i jak czytac
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [24]:
#zamiana yes/no na 1/0
encoder = OneHotEncoder(drop="first", sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [25]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [27]:
#Pandas get_dummies() funkcja

pd.get_dummies(data=df)

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0   False   False     True       False        False       True   
1   89.0   450.0    True   False    False       False         True      False   
2   99.0   300.0   False    True    False        True        False      False   
3  129.0   380.0    True   False    False       False         True      False   
4   79.0   410.0   False    True    False       False        False       True   

   gender_female  gender_male  bought_no  bought_yes  
0           True        False      False        True  
1          False         True       True       False  
2          False         True      False        True  
3           True        False       True       False  
4           True        False      False        True

In [28]:
#parametr drop first do usuwania pierwszej kolumny

pd.get_dummies(data=df, drop_first=True)

price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought_yes  
0        True  
1       False  
2        True  
3       False  
4        True

In [36]:
pd.get_dummies(data=df, drop_first=True, prefix='new') #dodaje slowo przed nazwa
pd.get_dummies(data=df, drop_first=True, prefix_sep='-') #dodaje - pomiedzy nazwami
pd.get_dummies(data=df, drop_first=True, columns=['size']) #wybrane kolumny sa prefixowane

color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes   False     True
1  green    male   89.0   450.0     no   False    False
2   blue    male   99.0   300.0    yes    True    False
3  green  female  129.0   380.0     no   False    False
4    red  female   79.0   410.0    yes    True    False

In [37]:
#standaryzacja danych biblioteka sklearn
# std() pandas nieobciazona
# std() numpy obciazony


print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie Standardowe: {df['price'].std():.4f}")



0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie Standardowe: 48.4768


In [48]:
#wystandaryzowane danych (oscylujemy blisko 0)
 (df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [50]:
#wystandaryzowane danych (oscylujemy blisko 0)
def standarize(x):
  return (x-x.mean()) / x.std()
standarize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [51]:
#wystandaryzowane danych (oscylujemy blisko 0) funkcja scale z skleanr(inne wartosci bo obciazony)
from sklearn.preprocessing import scale

scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [52]:
#funkcja standardscale lepsza od poprzedniej bo zapisuje wczesniejsze dane
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])





array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [54]:
#dodanie wartosci do danych
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [88]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [89]:
#Przygotowanie danych do modelu od poczatku wszystkie kroki
le = LabelEncoder() # tworzenie klasy labelencoder

df['bought'] = le.fit_transform(df['bought']) #przypisujemy to co bedzie z fit.transform do zmiennej df bought

scaler = StandardScaler() #tworzenie zmiennej scalar
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df = pd.get_dummies(data=df, drop_first=True) #uzycie get dummies i usuwanie niepotrzebnych kolumn
df #wyswietlenie danych

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1   False     True        False       True   
1 -0.691898  0.623610       0   False    False         True      False   
2 -0.461266 -1.603567       1    True    False        False      False   
3  0.230633 -0.415740       0   False    False         True      False   
4 -0.922531  0.029696       1    True    False        False       True   

   gender_male  
0        False  
1         True  
2         True  
3        False  
4        False