<a href="https://colab.research.google.com/github/danek121/machine-learning-course/blob/main/learning_machine/01_basics/04_linear_regressionBySKLEARN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
#przygotowanie danych
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])

m = len(X1)

print(f'Lata Pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')


Lata Pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [9]:
#zmiana rozmiaru danych
#6 wierszy 1 kolumna
X1 = X1.reshape(m, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [10]:
#generowanie wektora jedynek
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [11]:
#łaczenie metoda append()
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [12]:
#regresja liniowa z biblioteka sklearn
from sklearn.linear_model import LinearRegression


regression = LinearRegression()
regression.fit(X1, Y)

print(regression.intercept_) #wspolczynnik w0
print(regression.coef_[0])

2750.0
250.0
